---
- name: Admin RHV Network
  hosts: rhv
  become: true
  gather_facts: false

  vars_files:
    - files/rhv_vars.yaml
    - files/password.yaml
  
  pre_tasks:
    - name: Login to RHV
      redhat.rhv.ovirt_auth:
        hostname: "{{ engine_fqdn }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default{true} }}"
      tags:
        - always
  tasks:
    - name: create network
      ovirt.ovirt.ovirt_network:
        datacenter: Default
        name: mynetwork
        vlan_tag: 10
        vm_network: true 
    # Create bond on eth0 and eth1 interface, and put 'myvlan' network on top of it and persist the new configuration:
    - name: Bonds
      ovirt.ovirt.ovirt_host_network:
        name: myhost
        save: yes
        bond:
          name: bond0
          mode: 2
          interfaces:
            - eth1
            - eth2
        networks:
          - name: myvlan
            boot_protocol: static
            address: 1.2.3.4
            netmask: 255.255.255.0
            gateway: 1.2.3.4
            version: v4

    # Create bond on eth1 and eth2 interface, specifying both mode and miimon:
    - name: Bonds
      ovirt.ovirt.ovirt_host_network:
        name: myhost
        bond:
          name: bond0
          mode: 1
          options:
            miimon: 200
          interfaces:
            - eth1
            - eth2

    # Remove bond0 bond from host interfaces:
    - ovirt.ovirt.ovirt_host_network:
        state: absent
        name: myhost
        bond:
          name: bond0

    # Assign myvlan1 and myvlan2 vlans to host eth0 interface:
    - ovirt.ovirt.ovirt_host_network:
        name: myhost
        interface: eth0
        networks:
          - name: myvlan1
          - name: myvlan2

    # Remove myvlan2 vlan from host eth0 interface:
    - ovirt.ovirt.ovirt_host_network:
        state: absent
        name: myhost
        interface: eth0
        networks:
          - name: myvlan2

    # Remove all networks/vlans from host eth0 interface:
    - ovirt.ovirt.ovirt_host_network:
        state: absent
        name: myhost
        interface: eth0

    # Add custom_properties to network:
    - ovirt.ovirt.ovirt_host_network:
        name: myhost
        interface: eth0
        networks:
          - name: myvlan1
            custom_properties:
              - name: bridge_opts
                value: gc_timer=10