---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
     engine_fqdn: ansible-rhv-manager.example.com
     engine_user: admin@internal
     engine_password: Dung123456@
     engine_cafile: /etc/pki/ovirt-engine/ca.pem
     data_center_name: Default
     compatibility_version: 4.4

    #  clusters:
    #   - name: production
    #     cpu_type: Intel Conroe Family
    #     profile: production

     hosts:
      - name: ansible-compute-1.example.com
        address: 10.1.16.41
        cluster: Default
        password: Dung123456@

     storages:
       mynfsstorage:
         master: true
         state: present
         nfs:
           address: 10.1.16.43
           path: /data/mydata

    #    mytemplates:
    #      domain_function: export
    #      nfs:
    #        address: 100.101.102.104
    #        path: /exports/nfs/exported
    #    myisostorage:
    #      domain_function: iso
    #      nfs:
    #        address: 100.101.102.105
    #        path: /exports/nfs/iso

    #  logical_networks:
    #    - name: mynetwork
    #      clusters:
    #        - name: production
    #          assigned: yes
    #          required: no
    #          display: no
    #          migration: yes
    #          gluster: no

    #  host_networks:
    #    - name: myhost1
    #      check: true
    #      save: true
    #      bond:
    #        name: bond0
    #        mode: 2
    #        interfaces:
    #          - eth2
    #          - eth3
    #      networks:
    #        - name: mynetwork
    #          boot_protocol: dhcp

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        hostname: "{{ engine_fqdn }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  roles:
    - redhat.rhv.infra

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always