---
- name: Admin RHV Hosts
  hosts: rhv-manager
  become: true
  gather_facts: true
  
  tasks:
  - block:
    - name: Obtain SSO  token
      ovirt_auth:
        url: https://ansible-rhv-manager.example.com/ovirt-engine/api
        username: admin@internal
        password: Dung123456@
        ca_file: /etc/pki/ovirt-engine/ca.pem
    # Note that override_iptables is false by default in oVirt/RHV:
    - ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: ansible-compute-1.example.com
        address: 10.1.16.41
        password: Dung123456@
        override_iptables: true
        kernel_params:
            - intel_iommu=on
    # Deploy hosted engine host
    - ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: ansible-compute-1.example.com
        password: Dung123456@
        address: 10.1.16.41
        override_iptables: true
        hosted_engine: deploy

    # Maintenance
    - ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        state: maintenance
        name: ansible-compute-1.example.com

    # Restart host using power management:
    - ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        state: restarted
        name: ansible-compute-1.example.com

    # Upgrade host
    - ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        state: upgraded
        name: ansible-compute-1.example.com

    # Add storage domain
    - ovirt.ovirt.ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        name: ansible-nfs-server
        host: ansible-compute-1.example.com
        data_center: Default
        nfs:
            address: 10.1.16.43
            path: /data/mydata
    # Retry removing host when failed (https://bugzilla.redhat.com/show_bug.cgi?id=1719271)
    - ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: ansible-compute-1.example.com
        register: result
        until: not result.failed
        retries: 6
        delay: 20
    always:
    - name: Always revoke the SSO token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"